In [3]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("cars.csv")

In [7]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [9]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [13]:
df["fuel"].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [17]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

# 1. OneHotEncoding Using pandas

In [20]:
# to do that there is a method call .getdummies where we pass the dataframe and the columns to which we want to perform the onehotencoding

In [22]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

### Issue with One-Hot Encoding

One-Hot Encoding converts each category into a separate binary (0 or 1) column. While doing this, one common issue that can occur is the **Dummy Variable Trap**.

The Dummy Variable Trap happens because one encoded column can be predicted from the other columns. This creates duplicate information, which is called **multicollinearity**. It can affect the performance of some machine learning algorithms, especially Linear Regression and Logistic Regression.

**Solution:** We can avoid this problem by dropping one of the encoded columns using `drop='first'` in `OneHotEncoder` or `drop_first=True` in `pandas.get_dummies()`.

Another issue with One-Hot Encoding is that if a feature has many unique categories (for example, 500 different cities), it creates a large number of new columns. This increases memory usage and makes the model slower to train. This problem is known as the **Curse of Dimensionality**.

# 2.k1 Onehotencoding

In [26]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# 3. OneHotEncoding using sklearn

In [29]:
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2)

In [35]:
X_train.head()

         brand  km_driven    fuel                 owner
6362    Maruti      28180  Diesel           First Owner
6151   Hyundai      40000  Petrol          Second Owner
5462    Maruti      96000  Petrol  Fourth & Above Owner
560    Hyundai      10000  Petrol           First Owner
4464  Mahindra      45000  Diesel           First Owner

In [37]:
from sklearn.preprocessing import OneHotEncoder

In [43]:
ohe = OneHotEncoder(drop='first', sparse_output=False)

In [45]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [47]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [51]:
X_train_new.shape

(6502, 7)

In [55]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Maruti', 28180, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 40000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Maruti', 96000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Chevrolet', 50000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Honda', 7032, 0.0, ..., 0.0, 0.0, 0.0],
       ['Volvo', 2000, 1.0, ..., 0.0, 0.0, 0.0]], dtype=object)