In [3]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("customer.csv")

In [9]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [11]:
df = df.iloc[:,2:]

In [15]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [21]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [25]:
X_train

     review education
21  Average        PG
30  Average        UG
31     Poor    School
6      Good    School
39     Poor        PG
0   Average    School
42     Good        PG
1      Poor        UG
29  Average        UG
18     Good    School
27     Poor        PG
5   Average    School
45     Poor        PG
3      Good        PG
35     Poor    School
23     Good    School
24  Average        PG
38     Good    School
41     Good        PG
22     Poor        PG
15     Poor        UG
9      Good        UG
16     Poor        UG
17     Poor        UG
49     Good        UG
11     Good        UG
2      Good        PG
47     Good        PG
48     Good        UG
8   Average        UG
19     Poor        PG
43     Poor        PG
25     Good    School
32  Average        UG
26     Poor        PG
14     Poor        PG
7      Poor    School
4   Average        UG
44  Average        UG
46     Poor        PG

In [27]:
from sklearn.preprocessing import OrdinalEncoder

In [29]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [31]:
X_train = oe.fit_transform(X_train)
X_test = oe.transform(X_test)

In [33]:
X_train

array([[1., 2.],
       [1., 1.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [0., 1.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 2.]])

In [35]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [37]:
X_test

array([[1., 0.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.]])

In [39]:
from sklearn.preprocessing import LabelEncoder

In [41]:
le = LabelEncoder()

In [43]:
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [45]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [47]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0])